# 项目相关配置
jinke:
  # 名称
  name: JinkeMedia
  # 版本
  version: 3.2.0
  # 版权年份
  copyrightYear: 2019
  # 文件路径
  profile: D:/profile/
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务端口
  port: 8081
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://10.1.1.56:3306/jinkyx?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: JINK
        password: 1
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 10
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 50
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /monitor/druid/*
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#  profiles:
#    active: druid
  # 文件上传
  servlet:
     multipart:
       max-file-size:  256MB
       max-request-size:  256MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.jinke.project
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /
    # 验证码开关
    captchaEnabled: false
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 1440
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    #
    maxSessionLogin: false

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen:
  # 作者
  author: jinke
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.jinke.project.system
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀(类名不会包含表前缀)
  tablePrefix: sys_

# FastDFS配置
fdfs:
  #上传的超时时间
  so-timeout: 5000
  #连接超时时间
  connect-timeout: 1500
  #缩略图生成参数
  thumb-image:
    width: 150
    height: 150
  web-server-url: 10.1.1.238/
  storagePort: 8081/
  #TrackerList参数,支持多个
  tracker-list:
    - 10.1.1.238:22122

config:
  tempFilePath: D:\\temp\\
  aliappCode: 2d674c073ba84e6ab3c0f8c818c46ad5
  aliApiHost: http://blicence.market.alicloudapi.com
  aliApiPath: /ai_business_license
  aliIdCardApiHost: http://dm-51.data.aliyun.com
  aliIdCardApiPath: /rest/160601/ocr/ocr_idcard.json
  tess4j: tess4j/tessdata
  ssoBaseUrl: http://10.1.1.234:10010/ssoauth/api
  #sso平台公钥
  ssoPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxPTF7XO9ariJDoj6OhhvtJTB+cB/OEaeGyfyePgAE3OZ3uSZVHHaawoK+kUkqL5TExtZQ8/rC6GxRVvvdAq/guQ/Cxosnm5Xv+TOHxXhibmVo70dJwUkmNw/d8BWWcV10wFb6YNLwjWAAXZ+jn7nu+hTPjO0dGv5b0zA+/03YCDFxRID4G3CsWoxNFOZJT89LRURsKiIkEkDwy5crw9sDM/pcleI68W3riHVRuVnjaVKmbeAY42EYL0cQiVVztoYccCp4d11wYJkSMiedhBNOi7x2rwKmh8h3VrKeoDipATzAepFo3yDH95NaivZDAni4ta65hjQBJVRFewQDVmDCQIDAQAB
  #影像系统私钥
  ssoPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCDPqBdGgxEoxBgmX/fY2+k2fsduLhQ7bPqXoukFGbRvBSrjy6JKPbSlN3RRhkKWWWfsbB7jPhtS6UYj7OcXyaVJNUZHu0i2u5xCRTDMMCxqn64gAaK1DT5D1ssWyHnGq/dJCcHrCbBiqudTERPW04yyiA524DoNF45VsSaRViWJOHm0MHBxLWasUwjeFr/007cAPKF8cqJ6dZzGVp29O2p/OVqZic/U3yo9LDwdEbP5BjzQDHozu8sUH4HUoBcjiWA6O7PzFikbaGMDKWxL5pGSokP6+Pc2sFLOvV9D4qjWjw4D0Y9v5vRhacMQ+Xs/MQQDOMApwhUIlTCe+P4UFbNAgMBAAECggEAbl0NcPzkcBtHPFQYCXuOeGutFPMuWy9n6Z+TgWh+hcPJBfMjSMeftrjkRoTRrbg7EqzTITIL/axsqli8yrPgt+3/HF67PmInu/nM8c5fW4dphDB0T+3elclp+8Sun637UNSD1ZnYBUxcv6tQjgLToTYDH2QL5DeVPFZQgQHrWmV4aBJZTOobXAR96f7QGrspXoUSPxB1yvyvkaWM8Qu0icQb2Vj2KseWUH5mVGwOMNbnEPsLWuAD5dFJB6B2p8ZMgU5LSpfBAXLgq7ix/nifoIvqr2A7d1XleAi4F/0s3qeJgY7XHPQLYLNEfk2039/4Zr5t3vMhkg6igZ8fUGbo6QKBgQDEVB5u8Pkt1RPcwLZddyD+f+UptV7hfnYCp7EcT2vq/v9Dq0ZzYr8v8JoNJLVsn6aH8l3kKLmhnVGKcpuAiPuj2rHh+vyoorDgGT0hzRPoMg72qwUaoW++67WuYcbBn1NQFstjk2krqzTZOQMG0NCVSX3mqMMgAUu3MZKShTYG+wKBgQCrInkWa+Jf2/y6aeYXw2D5m0NsaSOry4NP4IdTe5CaSqBnQYyuuaXrMB++U2T7e0GbtOfbneWl+iWrnyaDEoeWuzU3lQSNaaI2TT4jfL+Wy/IDXrp1BmGmZbwvH94w8w+IsENaTNxGj9fyj9ctXa9yccKcN6EDb+OJNZjBfHBO1wKBgE7mh3yKd3nF4j+bay7Qy3+8InrKmyEAU6jpf7Ii8Pn2FNw7HwsMKk234hFaKVdIKgMEkls5SrD6qmR7fqb/ZjIJl+d7mMKk73SAcCL/afqs83qKbHixXFlcHR3BycDSqQbMwlx4R5H3MjwCP4cjsE/uwxxJwnFAVA+BaqhbxMS1AoGAZrwwMvybDm7y/jm6rsNUwSOrSzam+mgXMWmZ88z3Fxj7yGD6gp3idBkUxV4s/ieVUFM+6YGVrplH6gqFxSPnj95c6TwlWntyrOScDBPEtFNEuy8wAjbNgmYKncOk0H/p8GXYWSpRBm8t9WjShWJ7g9m1ObDPkU+nKeSqCmWYyksCgYBCb1ctxxeIiMCGaRC1AK+NpcmhGzsXK08PYNgiBuMgp32MsjaTngUC9gecwKO9U03xvm4/rvEQwg7gcn7g2W7K6k8HApNVj6fLsIeELdNXQ3D9TyNNI+eXOGTYorkMf28QRvFByvAkwola5ojM3XhWzYjLo0um42xnXt3IGvDtwA==
  #对外ip地址
  host: